### ISSUE TITLE
Pheonix setup

### ISSUE THREAD

**Issue by seastan** [mreishus/spades#179]
Is there anything I need to modify to get the the database running properly? So far I've managed to get the frontend up and running locally, and for the backend I am able to run mix phx.server, but it is throwing frequent errors:

`[error] Postgrex.Protocol (#PID<0.436.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"`

When I try to create a new account it throws an error status code 500, and the log shows:

`[error] #PID<0.8307.0> running SpadesWeb.Endpoint (connection #PID<0.8306.0>, stream id 1) terminated`
`Server: localhost:4000 (http)`
`Request: POST /api/v1/registration`
`** (exit) an exception was raised:`
 `   ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1896ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:`
`  1. By tracking down slow queries and making sure they are running fast enough`
`  2. Increasing the pool_size (albeit it increases resource consumption)`
`  3. Allow requests to wait longer by increasing :queue_target and :queue_interval`
`See DBConnection.start_link/2 for more information`

**Comment by mreishus** [comment]
It sounds like the database connection is not working at all.  The app tries to connect to a postgresql instance on `localhost` with username `postgres`, password `postgres`.  You need to make sure that is available; when it is, then running `mix ecto.setup` in the backend should do the initial database creation.  (Later, if any migrations are added to the project, `mix ecto.migrate` should apply them).

I just went through the process of getting it running on a new computer and wrote it up in the [main readme](https://github.com/mreishus/spades/blob/master/README.md).  The info in there or the [phoenix ecto guide](https://hexdocs.pm/phoenix/ecto.html) can possibly help out.  Let me know if you're still having problems after checking those.

**Comment by seastan** [comment]
Thanks for the more detailed readme. I was able to follow it and get the database running properly.
